server:
  port: 3000

spring:
  application:
    name: api
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: xty510521

dubbo:
  application:
    name: api
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20880