server:
  port: 3000

spring:
  application:
    name: api
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  data:
    redis:
      host: 8.134.107.55
      port: 6379
      password: .Xty510521

dubbo:
  application:
    name: api
  registry:
    address: nacos://8.134.107.55:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: 20880