server:
  port: 3000

spring:
  application:
    name: gateway
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: xty510521
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
