server:
  port: 3007

spring:
  application:
    name: feed
  data:
    redis:
      host: 8.134.107.55
      port: 6379
      password: .Xty510521
  datasource:
    url: jdbc:mysql:///dousheng
    username: root
    password: .Xty510521
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: feed
    qos-port: 22229
  protocol:
    name: dubbo
    port: 20887
  registry:
    address: nacos://8.134.107.55:8848
    username: nacos
    password: nacos

rocketmq:
  name-server: 8.134.107.55:9876