server:
  port: 3004

spring:
  application:
    name: favorite
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: xty510521
  datasource:
    url: jdbc:mysql:///dousheng
    username: root
    password: xty510521
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: favorite
    qos-port: 22226
  protocol:
    name: dubbo
    port: 20884
  registry:
    address: nacos://127.0.0.1:8848
