server:
  port: 3001

spring:
  application:
    name: auth
  data:
    redis:
      host: 8.134.107.55
      port: 6379
      password: .Xty510521

dubbo:
  application:
    name: auth
    qos-port: 22223
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://8.134.107.55:8848
    username: nacos
    password: nacos