server:
  port: 3001

spring:
  application:
    name: auth
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: xty510521

dubbo:
  application:
    name: auth
    qos-port: 22223
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://127.0.0.1:8848