server:
  port: 3002

spring:
  application:
    name: user
  data:
    redis:
      host: 8.134.107.55
      port: 6379
      password: .Xty510521
  datasource:
    url: jdbc:mysql:///dousheng
    username: root
    password: .Xty510521
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: user
    qos-port: 22224
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: nacos://8.134.107.55:8848
    username: nacos
    password: nacos
